org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_name=Chat Block
mod_id=chatblock
mod_version=1.4.1
mod_description=Multiversion mod that adds a filter list to block/hide sending and receiving custom spam chat messages
mod_archives_name=ChatBlock
base_group=tomeko.chatblock

java_version=[VERSIONED]
minecraft_version=[VERSIONED]
fabric_loader_version=0.19.3
fabric_api_version=[VERSIONED]
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0

oneconfig_version=1.0.0-beta.6
mod_menu_version=[VERSIONED]

stonecutter_version=0.9.5